# Generated by Django 4.2.6 on 2023-10-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gift_wrap",
            field=models.BooleanField(default=False),
        ),
    ]
