# Generated by Django 4.2.6 on 2023-10-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "catalog",
                "verbose_name_plural": "catalogs",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="catalog_cat_name_0890e6_idx")
                ],
            },
        ),
    ]
