# Generated by Django 4.2.6 on 2023-10-11 11:51

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=comment.models.comment_image_file_path
            ),
        ),
    ]
